title: "MAPS Lab: Modeling, Analytics, and Predictive Spatial Health Research"
url: "https://ruaaljuboori.github.io"
baseurl: "/MAPS-Lab"
theme: minima

header_pages:
  - projects.md
  - students.md
  - funding.md
  - products.md
